import { Metadata } from "next";
import NotFoundCompetent from "./components/NotFoundCompetent";

export const metadata: Metadata = {
  title: "Page Not Found | Think Arq - Think Build Disrupt",
  description: "Generated by Think Arq Studio",
  openGraph: {
    title: "Page Not Found | Think Arq - Think Build Disrupt",
    description: "Generated by Think Arq Studio",
    url: `https://thinkarq.com/`,
    images: "/meta-images/think-arq.jpg",
  },
  twitter: {
    card: "summary_large_image",
    title: "Page Not Found | Think Arq - Think Build Disrupt",
    description: "Generated by Think Arq Studio",
    images: "/meta-images/think-arq.jpg",
  },
};

function NotFound() {
  return (
    <div className="w-full h-screen">
      <NotFoundCompetent />
    </div>
  );
}

export default NotFound;
