import Link from "next/link";

import { Metadata } from "next";
import LottieAnimation from "./Components/LottieAnimation";
import { IoArrowForward } from "react-icons/io5";


export const metadata: Metadata = {
  title: "Page Not Found | Think Arq - Think Build Disrupt",
  description: "Generated by Think Arq Studio",
  openGraph: {
    title: "Page Not Found | Think Arq - Think Build Disrupt",
    description: "Generated by Think Arq Studio",
    url: `https://thinkarq.com/`,
    images: "/meta-images/think-arq.jpg",
  },
  twitter: {
    card: "summary_large_image",
    title: "Page Not Found | Think Arq - Think Build Disrupt",
    description: "Generated by Think Arq Studio",
    images: "/meta-images/think-arq.jpg",
  },
};

function NotFound() {
  return (
    <div className="w-full h-screen">
      <main className="flex flex-col items-center justify-center h-full py-25 bg-gray-50 text-center">
        <div className="max-w-100 max-h-100">
          <LottieAnimation path="/lottie/404-animation.lottie" width={300} height={300} />
        </div>
        <p className="text-lg font-space-grotesk text-gray-600 mt-4 mb-8">The page you’re looking for doesn’t exist.</p>

        <Link
          href="/"
          title="Home"
          aria-label="Home"
          className="font-quicksand text-lg text-(--color-text) flex items-center justify-center pt-2.5 pb-3 px-6 rounded-lg capitalize bg-(--color-gold-light) hover:bg-(--color-gold-hover) group transition-all font-semibold">
          <span className="flex items-center justify-start gap-3">
            <span>Go back home</span>
            <IoArrowForward className="text-2xl -rotate-45 group-hover:rotate-0 transition-all" />
          </span>
        </Link>
      </main>
    </div>
  );
}

export default NotFound;
